language: r
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN:
     - http://cran.rstudio.com
     - http://data-cleaning.github.io/drat/

notifications:
  email:
    on_success: change
    on_failure: change
