language: r
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

before_install:
 - Rscript -e "install.packages('validate', repos=c('http://cran.rstudio.com', 'http://data-cleaning.github.io/drat/'))"

after_succes:
 - Rscript -e "install.packages('covr', repos=c('http://cran.rstudio.com')"
 - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
