language: r
warnings_are_errors: false
sudo: required

r_binary_packages:
 - lpSolveAPI

cran:
 - http://cran.rstudio.com
 - http://data-cleaning.github.io/drat/

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
